app:
  url: # the base url of the app (default is http://localhost)
  port: # 7000 by default
  env: # anything other than 'production' will be treated as 'development'

database:
  mongo_url:
  logging: # the value you provide will be typecasted to boolean (0, '', false will be treated as false)

redis:
  host:
  port:
  db: # default is 0
  username:
  password:

jwt:
  secret:
  expiresIn: # should be a number (in seconds)
  refreshTokenSecret:
  refreshTokenExpiresIn: # should be a number (in seconds)

swagger:
  # basic swagger auth guard will be enabled if 'both' user and password are provided
  user:
  password:

rate_limit:
  storage: # 'memory' or 'redis' (default is 'memory')
  # global rate limit options (default is 10 requests per minute)
  global:
    ttl: # in milliseconds (default is 60000)
    limit: # number of requests (default is 10)
  # '/login' endpoint rate limit options (default is 5 requests per 5 minutes)
  login:
    ttl: # in milliseconds (default is 300000 ms, i.e. 5 minutes)
    limit: # number of requests (default is 5)

oauth:
  github:
    client_id:
    client_secret:
